version: '3'
services:
  api:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3001:3000'
    links:
      - db
  db:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    